### ISSUE TITLE
Validate message lock renewal

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.AzureServiceBus#146]
Add a test to prove that ASB SDK's message lock renewal is actually working

**Comment by SeanFeldman** [comment]
As part of this validation have run into issue where OnMessage API was not auto-completing messages that their callbacks where finished. This was due to a logical error we had in [`MessageReceiverNotifier.Stop()`](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/046a7a3476aebc89194e849dfe3a7c9154535dbd/src/Transport/Receiving/MessageReceiverNotifier.cs#L220) by forcing messageReceiver to close w/o waiting for it to mark all messages with completed callbacks as Completed.

**Comment by SeanFeldman** [comment]
Works as expected
