### ISSUE TITLE
Document how to set up High Availability

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.AzureServiceBus#2]
Make use of multiple servicebus namespaces in order to provide failover across namespaces.

**Comment by dylanmorley** [comment]
This is a feature that's becoming extremely important for our company - do you have an estimated date for this milestone?

There's some talk of moving away from nservicebus because paired namespaces aren't supported, but since we've invested time and effort into a number of services already, I'd rather we allocated some developers and contributed to this feature rather than going back to basics!

**Comment by yvesgoeleven** [comment]
Needs doco

**Comment by yvesgoeleven** [comment]
Duplicate of https://github.com/Particular/docs.particular.net/issues/368
