### ISSUE TITLE
Scenario with secured default connection is not working with SC involoved

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureServiceBus#235]
Originally discussed in #217, but scenario below doesn't work.

I tried to test SC with Beta4 and ran into an issue.
didn't use multiple namespaces, just tried to secure the default connection string

**Setup details**

* 2 endpoints (`Endpoint1` and `Endpoint2`) on the _same_ namespace
  * each does it via `transport.ConnectionString(connString));` ==> the [`default` name](http://docs.particular.net/nservicebus/azure-service-bus/securing-connection-strings) will be associated with the connString
* enabled `transport.UseNamespaceNamesInsteadOfConnectionStrings();` 
* `Endpoint1` send a message to `Endpoint2`
* `Endpoint2` throws an exception in the message handler
* error message gets into SC
* can retry from SC
* `Endpoint2` get the retried message and replies back to the originator (`Endpoint1`)
  * handler no longer throws
* exception thrown
```
NServiceBus.FirstLevelRetriesBehavior First Level Retry is going to retry message '58f8a8db-df60-473e-bbae-a6050117939e' because of an exception:
System.Exception: Invalid Queue path `Endpoint1@default` that cannot be used with Azure Service Bus. Queue path exceeds maximum allowed length or contains invalid characters. Check for invalid characters, shorten the name, or use `Sanitization().UseStrategy<ISanitizationStrategy>()` configuration extension.
```

**Comment by melkio** [comment]
Using `EndpointOrientedTopology` with default configuration, `AddressingLogic` implementation isn't able to handle composed destination (`queueName@something`). 
There is a sanitization strategy (`EndpointOrientedTopologySanitization`) that fix the issue.

A few questions before fixing the issue:

- why `EndpointOrientedTopologySanitization` isn't configured as default sanitization strategy for `EndpointOrientedTopology`?
- [here](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/develop/src/Transport/Addressing/Sanitization/Strategies/EndpointOrientedTopologySanitization.cs#L17) the point that fixes the issue. IMO it should be moved outside this class, inside `AddressingLogic` because it is worth for all possible topologies, isn't it?
- going through sanitization implementations they seemed weird to me: `EndpointOrientedTopologySanitization` sanitizes provided value only [if it's not valid](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/develop/src/Transport/Addressing/Sanitization/Strategies/EndpointOrientedTopologySanitization.cs#L27). But `AddressingLogic` already [checks if value is valid](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/release-7.0.0/src/Transport/Addressing/AddressingLogic.cs#L19) before invoking sanitization.
`ThrowOnFailingSanitization` throws if [provided value isn't valid](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/develop/src/Transport/Addressing/Sanitization/Strategies/ThrowOnFailingSanitization.cs#L23). It isn't a sanitization strategy concern, it's about validation.

@Particular/azure-service-bus-maintainers thoughts?

**Comment by SeanFeldman** [comment]
**Bullet point #1**

In version 7 users have to enable sanitization explicitly. `EndpointOrientedTopologySanitization` is for backwards compatibility. If you want endpoint-oriented topology but with custom sanitization rules (i.e. you don't have old version deployed), you're free to register your own sanitization strategy. By default we will accept everything that is valid.

**Bullet point #2**

> because it is worth for all possible topologies, isn't it?

Do you mean because it will apply to all topologies regardless of the sanitization strategy used?  That could be the case.

**Bullet point #3**

> going through sanitization implementations they seemed weird to me: EndpointOrientedTopologySanitization sanitizes provided value only if it's not valid. But AddressingLogic already checks if value is valid before invoking sanitization.

That's because `AddressingLogic` was added after sanitization strategies existed. As part of #230 I might need to change that. 

> ThrowOnFailingSanitization throws if provided value isn't valid. It isn't a sanitization strategy concern, it's about validation.

Correct. `ThrowOnFailingSanitization` doesn't perform validation. And by default it won't sanitize if validation is failing, so it's by default will throw if entities are invalid.

**Comment by SeanFeldman** [comment]
Also, to add to the bullet point #3, `EndpointOrientedTopologySanitization` always sanitizes the characters. Hashing is _solely_ performed when length is exceeding the maximum, which required validation (validation will only provide if path/name is too long since entity is sanitized for invalid characters before validation takes place in sanitization strategy).

**Comment by melkio** [comment]
> In version 7 users have to enable sanitization explicitly.
It's not correct: topologies setup default sanitization strategy during topology init phase. The default strategy is `ThrowOnFailingSanitization`for both topologies.
Could be better to configure `EndpointOrientedTopologySanitization` for `EndpointOrientedTopology` as default strategy?

What I wanted to say is that `ThrowOnFailingSanitization` isn't a santization strategy but a validation strategy that throws if validation reuls aren't satisfied.

@SeanFeldman about your last comment: `EndpointOrientedTopolgySanitization` is invoked by `AddressingLogic` (as the other sanitization strategies) only if validation rules aren't satisfied. Internal check about validation is useless.

**Comment by SeanFeldman** [comment]
> What I wanted to say is that ThrowOnFailingSanitization isn't a santization strategy but a validation strategy that throws if validation reuls aren't satisfied.

Correct. Unfortunately, the sanitization can't be applied in that case w/o some sort of validation. Do you have a different idea? Perhaps we should take it into a separate GH issue, to keep this one for the original issue?

**Comment by SeanFeldman** [comment]
Fixed via https://github.com/Particular/NServiceBus.AzureServiceBus/commit/e1a38fb341cb539b570b37aebd081a385786cab2
