### ISSUE TITLE
Validate default values

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.AzureServiceBus#241]
The following seems to be different than intended

1. [x] BrokeredMessageBodyType (Byte[] for EndpointOriented & Stream for Forwarding?) ==> correct
1. [ ] MaxDeliveryCount (10 for queues, 6 for subscriptions)

**Comment by SeanFeldman** [comment]
Validated that `BrokeredMessageBodyType` is *always* set to `byte[]` by default, regardless of the topology used. In order to be something else, the transport has to be explicitly instructed using `.BrokeredMessageBodyType()` configuration API. 
Checked the [doco](http://docs.particular.net/nservicebus/azure-service-bus/configuration/full#controlling-connectivity), it's correct and stating that `byte[]` is the default.

**Comment by SeanFeldman** [comment]
`MaxDeliveryCount` for subscriptions will be fixed by PR  #243

**Comment by SeanFeldman** [comment]
Closed via https://github.com/Particular/NServiceBus.AzureServiceBus/commit/0613281cb60eb5b20f11c53d14ef7c091e2e28e3
