### ISSUE TITLE
Configure EndpointOrientedTopologySanitization as default for EndpointOrientedTopology

### ISSUE THREAD

**Issue by melkio** [Particular/NServiceBus.AzureServiceBus#253]
`EndpointOrientedTopology` configures `ThrowOnFailingSanitization` as default sanitization strategy [here](ThrowOnFailingSanitization)

Is it right? Should `EndpointOrientedTopologySanitization` be better for backward compatibility?

**Comment by SeanFeldman** [comment]
Briefly touched on this in my [comment](https://github.com/Particular/NServiceBus.AzureServiceBus/issues/235#issuecomment-223880641) on the original issue. Here's the idea:

`EndpointOrientedTopologySanitization` was the only topology we've supported in the past. Moving forward, we have 2 topologies: `EndpointOrientedTopologySanitization` and `ForwardingTopology`, which users can choose from. New users, while encouraged to use `ForwardingTopology` still can decide to go with the older topology. That doesn't mean that we _have to_ force the same sanitization rules we had in v6 and prior of the transport. 

By making `ThrowOnFailingSanitization` the default sanitization for `EndpointOrientedTopology` we're allowing new users that use the topology to decide how _they_ want to sanitize their entities (or make those entities follow the rules and not sanitize at all) rather than making that call for them. They can choose `EndpointOrientedTopologySanitization` if would like to **opt-in** for that type of sanitization.

Does that answer the question?

**Comment by yvesgoeleven** [comment]
Renamed to ValidateAndHasIfNeeded, not the default
