### ISSUE TITLE
ICreateQueues implementation doesn't use queueBindings provided value

### ISSUE THREAD

**Issue by melkio** [Particular/NServiceBus.AzureServiceBus#283]
`TransportResourcesCreator.CreateQueueIfNecessary` receives `QueueBindings` as first parameter with all needed info about resource names to create, but this implementation doesn't pass this value to `ITopologySectionManager` dependency.

`ITopologySectionManager` implementations use `EndpointName` from settings as input queue name

**Comment by yvesgoeleven** [comment]
What is in the QueueBindings? What are we supposed to do with it?

**Comment by SeanFeldman** [comment]
`QueueBinding` is another core concept introduced in v6, but never documented.

`ITopologySectionManager` is using `settings.EndpointName()` to determine endpoint`s name.  We do it this way because `QueueBinding`s passed into `TransportResourcesCreator` have `ReceivingAddresses` and `SendingAddresses` collections of strings. For receiving addresses, `string` is not enough to determine endpoint`s input queue.

I, personally, do not understand when core is invoking `ICreateQueues` and what is passed into `queueBindings.ReceivingAddresses` parameter.

**Comment by SeanFeldman** [comment]
Additional question, what is `identity` argument passed into `ICreateQueues.CreateQueueIfNecessary`. It's not used anywhere, unlike `QueueBindings` that is eventually used.

**Comment by SeanFeldman** [comment]
Separate issue (#287) opened for the `identity`.

**Comment by SeanFeldman** [comment]
Resolved via https://github.com/Particular/NServiceBus.AzureServiceBus/commit/18aca9f239803481abac23ce736048b9fab2cc89
