### ISSUE TITLE
Document how to work with native body content

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.AzureServiceBus#32]
Currently we assume the body content of a message is sent in the form of a byte[], but native integrations can also send it as a string or as a stream... we should make it possible to quickly change this, right now it requires swapping out parts of the receive infrastructure, which isn't so trivial.

Things to do:
- [x] Implement option to control body serialization (~~PR https://github.com/Particular/NServiceBus.AzureServiceBus/pull/88~~)
- [x] DLQ poisonous messages (~~PR https://github.com/Particular/NServiceBus.AzureServiceBus/pull/89~~) 
- [x] Add/update [native integration sample](http://docs.particular.net/samples/azure/native-integration-asb/) for v7 (~~PR https://github.com/Particular/docs.particular.net/pull/1052~~)
- [x] Auto-detect and process any body type (interoperability with older endpoints)
- [ ] Document (`AzureServiceBusSerializationSettings`, interoperability, and backwards support)

**Comment by abombss** [comment]
This seems related to my #8

**Comment by yvesgoeleven** [comment]
@abombss Yes it is, but it's not a trivial thing. As the client is actually in control of this it could differ on a per message basis. But we have no way of knowing what is in the brokeredmessage, there is no header or metadata for this...

**Comment by yvesgoeleven** [comment]
@abombss PS: we cannot use content type header for this as that is already taken for xml/json

**Comment by SeanFeldman** [comment]
@yvesgoeleven  should we close this since we have control over how body is serialized with [`AzureServiceBusSerializationSettings`](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/14b3be1da9838f22634fa32a0bf0bca1e45ab550/src/Transport/Config/ExtensionPoints/AzureServiceBusSerializationSettings.cs#L17)?

**Comment by yvesgoeleven** [comment]
no, we do this differently in vnext and still need to document the changes

**Comment by abombss** [comment]
I can't say I am a fan of this approach.  The receive should negotiate the format using headers, it should not have to be defined as part of the endpoint configuration.  It should also support fallback and be backwards compatible.

Today, messages are sent as wcf serialized byte arrays.  So using GetBody<Stream> will always fail, in vnext it will use streams.  So why not set a property on the Send that indicates the format.  The receive can check the property if it exists, use that to get the raw data, if not try a Stream, if the Stream fails then fallback to byte[].

I also think this approach could be applied to update existing NSB.ASB 5.x and 6.x clients so they would be able to handle the new 7.x streams without forcing a whole NSB version upgrade on them.

**Comment by SeanFeldman** [comment]
@yvesgoeleven right, now it's a part of the transport extension API defined on BusConfiguration...

@abombss we had that discussion as well. Ideally, MSFT ASB team to provide that information on a brokered message. Otherwise it would need to be a custom header as you suggest. @yvesgoeleven should we re-evaluate how we do it?

**Comment by SeanFeldman** [comment]
@abombss we can't rely on the custom header, because when a message comes from a 3rd party as a native message, that custom header might not be there at all. Which leads us back to relying on the `BrokeredMessage` to provide that information. 

I have pinged MSFT ASB team to help with that.

**Comment by abombss** [comment]
That is what content type and encoding headers are for, no different than
http. I really don't see this as an asb issue, its a defect from the
original version of the transport.

It can still be handled gracefully with proper fallback. It should be
stream by default with byte array as legacy fallback. Maybe it's also worth
testing what an amqp java library writes on the wire and a simple rest call
to ASB api. I am assuming streams could work fine there too.

Either way it has to have backwards compatibility, if it doesn't we would
need a stop the world big bang upgrade of all our endpoints to get basic
interop.

We are doing more and more xplat and interop now so this is a huge blocker
for us.

**Comment by yvesgoeleven** [comment]
Imo content type is already used to differentiate xml, json, etc... it cannot be reused for the second level serialization that asb is doing internally. BrokeredMessage does not have an encoding option either (we assume UTF8 now). So all we can do is add additional headers

**Comment by abombss** [comment]
Brokeredmessage also has a totally custom property bag, adding an encoding
header to account for things like compression, encryption, serialization
format so I don't see how this an issue. Also, if sticking to http
standards there is nothing wrong with appending parameters / options to the
header value.

Example of json that is using a stream that is compressed.

Content-Type: application/json
Content-Encoding: octect/stream, gzip

Example using the current wcf serialized byte array.

Content-Type: application/json
Content-Encoding: wcf/bytes, gzip

If you follow http standards and implement content negotiation on the
receive this should be pretty trivial to accept and handle anything and
also make it extensible.

The biggest issue is still backwards compatible with nsb 4.x and 5.x.

We would be fine upgrading our 4.x and 5.x endpoints to handle the new
capabilities, but we cannot force a stop the world big bang upgrade.

**Comment by yvesgoeleven** [comment]
We can surely do this, but I still consider it custom even if we would follow http names and in a native integration scenario it would still have to be communicated by the implementing team to the integrating team as being a customization. Would have been better if we could rely on something native in the brokered message

**Comment by LiamFeldman** [comment]
Definition of [BrokeredMessage.ContentType](https://msdn.microsoft.com/en-us/library/microsoft.servicebus.messaging.brokeredmessage.contenttype.aspx) says:
> The type of the content of the message body. This is a content type identifier utilized by the sender and receiver for application specific logic.

As such, it shouldn't be used to describe the *serialization* used by ASB.

**Comment by SeanFeldman** [comment]
`BrokeredMessage.ContentType` is not currently used by NSB.ASB.
The following logic be applied:

1. On the incoming messages, always use `BrokeredMessage.ContentType` to determine how to access message body. Empty == byte array [default], `application/octet-stream` == stream. This way we can also stay backwards compatible. 

1. `BrokeredMessageBodyType` convention to be used to set `BrokeredMessage.ContentType` on the _outgoing_ messages. If body is is a stream,assign `application/octet-stream`, otherwise leave it empty.

**Comment by abombss** [comment]
I would not use application/octect-stream for content type since this technically means a binary file.  Why not stick with what HTTP does and use application/xml or application/json and blank would still just be a byte array.  I am hoping at some point we actually get content negotiation on the receive side inside of coupling subscribers to the content-type of the publisher.  Or as this is technically a transport encoding issue add a Transport-Encoding header "application/octect-stream" vs "wcf/byte-array" or something.

**Comment by SeanFeldman** [comment]
@abombss this transport encoding, not content type. Content type is already communicated via `NServiceBus.ContentType` NSB header. The reason not to use any value for a body of `byte[]` is to be backwards compatible with endpoints on the older version of the transport, that are by default use byte array.

@Particular/azure should we rather than using `BrokeredMessage.ContentType` introduce a custom header?

**Comment by abombss** [comment]
I would prefer a custom header for Transport-Encoding. Content-Type is a standard header and has standard meaning coming from the very well known world of HTTP.  As stated in one of my other older issues from 2 years ago (https://github.com/Particular/NServiceBus.Azure/issues/106), the transport probably should have been promoting NServiceBus.ContentType to the BrokeredMessage.ContentType and on the receive reading that as the ContentType, again to help with interop.  

I find it interesting that we don't want to introduce a custom header for something truly custom like serialization format, but we would do it for something very standard like Content-Type, or worse confuse the concept of Content-Type even more by having 2 similar headers each with different meanings.

I would define the rules in the following manor.
Sending
==
1) Update NSB.ASB 5.x.x, 6.x.x, 7.x.x
  * Define configuration parameter to use Byte\[\] or Stream on Send
    * 5 & 6 should default to Byte\[\] and 7 should default to Stream (breaking change!)
  * Write BrokeredMessage.Properties["Transport-Encoding"] = application/octect-stream or wcf/byte-array depending on whats configured.  Legacy endpoints and bad interop endpoints would not have a Transport-Encoding property defined.

Receiving
==
* Check for BrokeredMessage.Properties["Transport-Encoding"]
  * If exists, read body using appropriate deserialization technique to create the receive body stream.
    * If read fails, log and move to DLQ, no point in retrying its poison
  * If not exists, try byte\[\] _This should fail if using interop since this requires the sender to explicitly use a byte\[\] for sending which is typically never done outside of NSB_.
    * If byte\[\] fails, fallback to Stream
    * If Stream fails, its poison; Log and DLQ, no point in retrying

Upgrading
==
1) Upgrade all subscribers (endpoints that send no messages) first to latest minor version of the transport.
2) Upgrade all sending endpoints with latest minor version of the transport keeping byte\[\] serialization.
3) Reconfigure legacy sending endpoints to use new stream based serialization.
4) Happily deploy any newer versions of the transport and move forward with no technical debt :yum:

The key for me is the backwards compat with the legacy endpoints so we can gracefully upgrade our endpoints.

**Comment by SeanFeldman** [comment]
@abombss custom header is OK.

**Comment by SeanFeldman** [comment]
@abombss poisonous messages will be going to DLQ :)

**Comment by abombss** [comment]
:) -- Make sure its BrokeredMessage.DeadLetter( new Dictionary<string,
object>() { } ) with properties and info why it failed.

**Comment by SeanFeldman** [comment]
Yes, passing [reason and details](https://github.com/Particular/NServiceBus.AzureServiceBus/pull/89/files#diff-446ccf5d2a05a3320ebaf7992c901021R125)

**Comment by yvesgoeleven** [comment]
Replaced by https://github.com/Particular/docs.particular.net/issues/886
