### ISSUE TITLE
Decoupling endpoints from the physical queues and using topics

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureServiceBus#342]
The topologies we had so far (`EndpointOriented` and `Forwarding`) assume that an endpoint has to have an input queue known to other endpoints for sending messages. By having a designated queue per endpoint, we're losing the flexibility and the following abilities:
- Deduplication on the business message level
- Native message auditing / backup
- Wiretap
## De-duplication on the business message

With endpoints coupled directly to the receiving endpoints, messages be deduplicated either by NSB using native method or by using the Outbox feature. The drawback on the native deduplication is that it only operates on the native transport message ID and only for a certain period of time, leaving potential for failures if duplicates happen after defined period of time. The drawback of the NSB Outbox feature is that it requires a fairly complicated setup for deduplication to work and often it's not aligned with what customers would like to do.

By decoupling endpoint from a queue, there's an option to have an input queue that can allow custom de-duplication on a business message level. Properties required for de-duplication could be promoted to the headers and messages could go through an additional processing defined by customers to filter out duplicates. Once messages are de-duplicated, they could be forwarded to enpoints` designated subscription.
## Native message auditing / backup

By sending all commands to a queue, we remove ability to audit and backup messages. In case an input queue is decoupled from an endpoint using designated topic/subscription, it will be possible to audit /backup messages natively.  

@Particular/azure-service-bus-maintainers any thoughts?

**Comment by abombss** [comment]
Yes, this is the topology we have been running since v4 with customizations. Topics for all sends / publishes, queues only for consumption. It gives us lots of flexibility. Further the pattern can be simplified with a single inbox (queue) per endpoint and an outbox (Topic not to confuse terminology) for all sends. Routing is all done based on type / channel so no endpoint needs to know about the physical location of any other endpoint. The coupling is only on a logical message channel. I never liked nsb being so tightly coupled to physical locations given Udi preaches logical coupling in his ADSD. 

I am not sure I see the benefit of consuming from a subscription directly. I would have the subscription still forward to a queue. This is crucial for replay to an endpoint. We never replay to topics since that can have unintended consequences, especially with commands, we only to queues for endpoints that failed.

**Comment by SeanFeldman** [comment]
@abombss that's exactly what I had in mind. While operations such as sends will not be as performing as sends to queues directly (due to some expected latency on the broker), the benefits of having decoupling and additional features outweigh it.
