### ISSUE TITLE
Document MessageReceiver/MessageSender settings

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.AzureServiceBus#42]
This would allow amqp as a protocol underneath
[MessageReceiver](https://msdn.microsoft.com/en-us/library/microsoft.servicebus.messaging.messagereceiver.aspx)
[MessageSender](https://msdn.microsoft.com/en-us/library/microsoft.servicebus.messaging.messagesender.aspx)

**TODO**
- [ ] Documentation on configuration options

**Comment by abombss** [comment]
:+1: this also would allow for unique topologies where the send and receive entities are not forced to be queues or topics, for example like sending audit and error messages to topics instead of queues or having commands sent via a topic instead of a direct queue.

AMQP has lots of limitations right now compared to SBMP, no transactions and no support for partitioned entities, but overall this is a much better abstraction to use.

**Comment by abombss** [comment]
FYI, if NSB will support native Scheduled Messages with Cancellation, the Azure SDK will require a special API call using the QueueClient and TopicClient directly, it did not look like from the new 3.x SDK that those types of calls would be supported using MessageSender and MessageReceiver.

**Comment by yvesgoeleven** [comment]
Currently NSB has no support for cancellation of sheduled messages, but if it ever will, then the config model of vnext will allow us to swap it out easily for a queueclient or topicclient based implementation. In vnext we have abstracted away all ASB specific API's for both testing and configuration purposes

**Comment by SeanFeldman** [comment]
@yvesgoeleven since our receivers are based on `MessageReceiver`/`MessageSender`, should we close this issue?

**Comment by yvesgoeleven** [comment]
still needs doco on configuration options

**Comment by yvesgoeleven** [comment]
Replaced by https://github.com/Particular/docs.particular.net/issues/1261
