### ISSUE TITLE
Replace the concepts of IManageMessageSenderLifeCycle & IManageMessageReceiverLifeCycle

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus.AzureServiceBus#447]
We think that we can get rid of `IManageMessageSenderLifeCycle ` and `IManageMessageReceiverLifeCycle` since we know that the relationship between factories, receivers and senders should be one to one. 

We propose to favor this one over #362 

Connects to https://github.com/Particular/NServiceBus.AzureServiceBus/issues/587

**Comment by yvesgoeleven** [comment]
@danielmarbach probably the other way around, we can get rid of the factory lifecycle manager, connections will drop so a lifecycle manager is needed at this level, but each time a new sender or receiver must be created we can also create a new factory

**Comment by SeanFeldman** [comment]
I think the intent was to get rid of the `CircularBuffer` internally as well.
I.e. create the entities and when trying to get those and find that connection was closed, new it up.
Thoughts @yvesgoeleven @danielmarbach ?

**Comment by yvesgoeleven** [comment]
you need some kind of even distribution when using those entities, that's what the circularbuffer is there for, easy way to alternate. If you want to get rid of it you'll need to introduce another way of alternating

**Comment by danielmarbach** [comment]
@yvesgoeleven @SeanFeldman could we get on a call? I have difficulties to understand it since I'm still lacking in those ASB areas.

**Comment by SeanFeldman** [comment]
@danielmarbach Monday would work?

**Comment by danielmarbach** [comment]
Yes

**Comment by yvesgoeleven** [comment]
A short explanation why we need to alternate between entities (actually we need to alternate between connections).

The answer lies in the internal architecture of ASB, which from a high level looks like this:

 * DNS & azure edge network assign connections to a specific gateway node inside a scale unit of tthe broker
 * gateway node is responsible for connectivity, security, throttling and broker node lookup
 * broker node is responsible for actually executing operations on the message store

![internal architecture](https://cloud.githubusercontent.com/assets/471354/21094507/9e923d32-c057-11e6-9703-040815fd5f93.png)

Every time a new messaging factory is created it establishes a network (tcp or websockets) connection with a node on the gateway of the broker.  Because of the sheer number of available gateway nodes, each connection probably ends up on another node.

![connectivity](https://cloud.githubusercontent.com/assets/471354/21094518/a2de9656-c057-11e6-817b-30444aef58d3.png)

This connection is established & maintained as long as the messaging factory lives, or as long as the gateway node decides to serve the connection. If a gateway node gets to much traffic it will start throttling all of its connections (regardless of their actual usage, in asb doco this is referred to as the 'noisy neighbour' problem), and even close them if needed.

So we want multiple messaging factories to establish a connection with multiple gateway nodes and alternate between these so that we can distribute the load. This ensures that we are less susceptible to this noisy neighbour problem, it reduces the impact of throttling and connection loss as only a percentage of our throughput is lost at that point and not all of it.

The ringbuffer is in place to ensure we alternate between connections, if we ever decide to use another structure for managing our pool, we should ensure not to loose the alternating behavior.

**Comment by danielmarbach** [comment]
@yvesgoeleven provided a good explanation about why the circular buffer is needed. Closing this.
