### ISSUE TITLE
Support for overridden local address is broken

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.AzureServiceBus#619]
The test When_publishing_with_overridden_local_address, overrides the local address 

`builder.OverrideLocalAddress("myinputqueue");`

it creates the following topology

![image](https://user-images.githubusercontent.com/471354/30744686-877576e2-9fa3-11e7-8795-937a7b6a16f7.png)

Note how the transport creates 2 input queues

one for the endpoint name and one for the overriden local address
the subscription has a forwarding rule set up  to route to the endpoint named one, and not the overridden local address

**Comment by yvesgoeleven** [comment]
TopologySection manager bases itself on endpoint name and does not take this override into account

https://github.com/Particular/NServiceBus.AzureServiceBus/blob/develop/src/Transport/Topology/Topologies/ForwardingTopologySectionManager.cs

The override can be found in a setting called "BaseInputQueueName"

**Comment by yvesgoeleven** [comment]
Fixed in https://github.com/Particular/NServiceBus.AzureServiceBus/commit/47b40787eda3f9d3158fd5995939c09d81fb6881

**Comment by SeanFeldman** [comment]
Not quite. Using `BaseInputQueueName` bypasses what core is doing and can cause in some scenarios incorrect behavior (edge cases, I have hard time to identify).

What we _should_ be doing is using `settings.LocalAddress()` that consolidates `BaseInputQueueName` in the `SharedQueue`.

I'm going to raise a PR.

**Comment by SeanFeldman** [comment]
Reason why we can't just use `NServiceBus.BaseInputQueueName` setting is because it goes through transport translation in the [Receiving feature](https://github.com/Particular/NServiceBus/blob/8c8332c30c7e0de929aa028b5216a5da99211dbd/src/NServiceBus.Core/Transports/Receiving.cs#L7-L33) and the result is stored in `NServiceBus.SharedQueue` which is exposed by `settings.LocalAddress`. 

Features are not created prior to transport infrastructure Initialization is invoked. Therefore `NServiceBus.SharedQueue` is not available yet, and using `NServiceBus.BaseInputQueueName` is ignoring what the core will be doing with it. By reading directly the value from `NServiceBus.BaseInputQueueName` we're violating the contract and expectations set by the core and running into possibility to have a wrong value. I'm addressing this in #620 and would appreciate an extra eyes on it.

**Comment by yvesgoeleven** [comment]
I'm not mad about this approach, better that we apply transport address translation ourself at startup, the transport owns that code anyway

**Comment by SeanFeldman** [comment]
> better that we apply transport address translation ourself at startup, the transport owns that code anyway

This is were our opinions are not aligned. Whenever we have a Core abstraction that is in place and we deliberately bypass it at the downstream version, we're just setting ourselves up for more problems later.
I'm in favour of reviewing #620 before concluding what we should or should not do. Just like we should weigh carefully if this fix should be ported back.

Let's finish discussion on the `settings.LocalAddress()` approach in #620 and if it proves to be a deadend, we'll continue here.

**Comment by danielmarbach** [comment]
https://github.com/Particular/NServiceBus.AzureServiceBus/pull/620 was merged. Should we close this?

**Comment by SeanFeldman** [comment]
Closed via https://github.com/Particular/NServiceBus.AzureServiceBus/commit/5c1d8408f227988df8a1a4a01e5d9096b4e9f57c
