### ISSUE TITLE
Perform namespace cleanup after ATTs executed

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureServiceBus#634]
Add a single explicit test that can be triggered from TC build configuration step to with `dotnet test` at the end of ATTs steps to remove all ASB entities.

**Comment by yvesgoeleven** [comment]
As we have multiple namespaces configured, how do we now what we will clean up this way?

**Comment by yvesgoeleven** [comment]
Why are we doing this btw? Will it run for every test set? If so we will severely extend the time it takes to execute them

**Comment by danielmarbach** [comment]
@yvesgoeleven sorry we discussed this on Friday in the sync after you left. One of the discussion points I raised was that after we cleaned the existing namespaces we started a few tests failing. We started to think about different ways of cleaning the namespaces to mitigate that risk. Furthermore, we recaped the different ways that we had in the past to clean the queues and topics (in the cleanup method of the IConfigureTestExecution implementation) and how the current message stamping is far superior to that. Still, we figured if we could come up with a fast and simple way to clean all queues and topics after all ATTs where run (when TC holds still the connection string lock) we might be able to detect other issues since we can assume a clean namespace for each run. We discussed that a simple explicit test that runs at the end of the build pipeline is probably good enough to get started. The side effects of the queue deletion being an asynchronous operation should also be mitigated since the next build that kicks in takes a few minutes to compile first.

**Comment by yvesgoeleven** [comment]
We can try it one more time ofcourse, but previous attempts at this in the past always resulted in us going back to existing queues to start from. Creation has always been a slow point of the broker

**Comment by SeanFeldman** [comment]
You're absolutely correct. And there can be times where builds will fail because we are timing out on entity creation. PR #635 is an experiment and we can disable it from within TC if need.

> Will it run for every test set?
It will run per build configuration, at the end. I.e. once ATTs for each topology are done executing.

> If so we will severely extend the time it takes to execute them
Not really. If no failures, then it takes a few seconds. Worse case scenario, it will take 25 seconds (5 attempts with 5 sec backoff).

**Comment by SeanFeldman** [comment]
About times - I have optimized the deletion and it takes from 40 to 90 seconds. Prior to that, deletions were failing on topics and taking longer.
