### ISSUE TITLE
 Guard.AgainstUnsetSerializerSetting() is performed too early

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureServiceBus#654]
`DefaultConfigurationValues. Apply(SettingsHolder settings)` is responsible to set the defaults for the transport.  

Recently, when the [default serializer was  removed](https://github.com/Particular/NServiceBus.AzureServiceBus/pull/615), a guard for configured serializer was added.

https://github.com/Particular/NServiceBus.AzureServiceBus/blob/ae916363d89057349d9264490f7cfc2cacfcfd1b/src/Transport/Config/DefaultConfigurationValues.cs#L13

I've ran into an issue with the timing of this code when running NSB.Bridge, that uses NSB.Raw. The transport is throwing an exception as it doesn't find the default serializer registered by Core.

Should this check be executed where defaults are set by the transport or should it be moved closer to the point where the transport needs to be started?

/cc @SzymonPobiega

**Comment by danielmarbach** [comment]
How about doing it in the ctor of `AzureServiceBusTransportInfrastructure` or here https://github.com/Particular/NServiceBus.AzureServiceBus/blob/develop/src/Transport/Config/AzureServiceBusTransportInfrastructure.cs#L56

**Comment by SeanFeldman** [comment]
Calling it in `InitializeIfNecessary()` is probably better. Then we know that all configurations are finalized.

**Comment by SzymonPobiega** [comment]
My $.02: from the NServiceBus.Raw perspective it does not really matter because it needs to hack it anyway (unless there is a way to only run this check if actual serialization happens -- which is not the case in Raw). That said, ASB is not the first offender since MSMQ requires error queue to be present in `errorQueue` setting key to work.

As Raw maintainer I've been (unsuccessfully) pushing in the direction where transport seam is respected as the only way to pass information from the core to the transport and there is no "smuggling" of data in the settings bug. Each time such "smuggling" is done, Raw needs a hack to deal with it.

**Comment by SeanFeldman** [comment]
> As Raw maintainer I've been (unsuccessfully) pushing in the direction where transport seam is respected as the only way to pass information from the core to the transport and there is no "smuggling" of data in the settings bug. Each time such "smuggling" is done, Raw needs a hack to deal with it.

@SzymonPobiega a) agree. b) is there a related PlatDev issue we could link this to?
