### ISSUE TITLE
MaxDeliveryCount does not update

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.AzureServiceBus#677]
@janpieterz reported that last beta does not update the MaxDeliveryCount anymore

**Comment by danielmarbach** [comment]
Wait what? How is that possible?

**Comment by SeanFeldman** [comment]
@janpieterz / @yvesgoeleven steps to repro?

**Comment by janpieterz** [comment]
On my end it was as fairly normal setup, using `FailOverNamespacePartitioning` (and a custom one), and the following:
```
var receivers = transport.MessageReceivers();
receivers.AutoRenewTimeout(TimeSpan.FromMinutes(10));
var queues = transport.Queues();
queues.LockDuration(TimeSpan.FromMinutes(5));
queues.MaxDeliveryCount(100);
var subscriptions = transport.Subscriptions();
subscriptions.MaxDeliveryCount(100);
subscriptions.LockDuration(TimeSpan.FromMinutes(5));
```

The lock duration here is respected (changing from 5 to 3 will effectively change) but the MaxDeliveryCount isn't, always ended up being either 10 or 6.

If it'd be my guess this is where to look for the queues:
https://github.com/Particular/NServiceBus.AzureServiceBus/blob/develop/src/Transport/Creation/AzureServiceBusQueueCreator.cs#L34
and this for subscriptions:
https://github.com/Particular/NServiceBus.AzureServiceBus/blob/develop/src/Transport/Creation/AzureServiceBusSubscriptionCreator.cs#L32

**Comment by SeanFeldman** [comment]
What's the recoverability settings, the default NServiceBus provides?

**Comment by janpieterz** [comment]
Jup! For ease of this I just sent you the whole NSB configuration (Email). 
Sorry can't make repro atm, bit busy, I can make one tomorrow morning (UTC+1) if needed.

**Comment by SeanFeldman** [comment]
Then I'm relieved. It's not a big, but a concious design decision.

In the past, we didn't tie recoverability to the delivery counts which
could result in message dead-lettering because of concurrent processing. As
a workaround, it was required to set delivery count to something
unrealistically large to avoid false dead-lettering.

 From version 7 of the transport, we've addressed the issue. No message
will be dead-lettered because of concurrent processing as recoverability is
using the DeliverCount days provided by every Brokered Message.

For system queues, such as audit and error, we set an arbitrary number (10)
as those are normally not processed by competing consumers.

Do you think this is still a bug?

**Comment by janpieterz** [comment]
Doesn't sound like it's a bug indeed, is the option then only in there for custom recoverability settings? 

I do think if I specify it directly it should respect that over the default setting, but for us we just used it to indeed prevent some false dead lettering so that's more of a 'design' question than a bug. I'll remove the specification from our configs.

**Comment by yvesgoeleven** [comment]
@SeanFeldman right, I remember now. Do we issue a warning if the 2 settings mismatch?

**Comment by SeanFeldman** [comment]
> we just used it to indeed prevent some false dead lettering

Exactly for this reason I think we shouldn't let the ghosts of the past hunt customers today. NServiceBus ASB transport handles the setting and customers should not set it manually. Suggest to close the issue 🙂

**Comment by SeanFeldman** [comment]
> Do we issue a warning if the 2 settings mismatch?

We should probably remove the public API to set `MaxDeliveryCount` so it doesn't confuse users.

**Comment by SeanFeldman** [comment]
☝️ will be handled as a separate issue for transport v8 and above.
