### ISSUE TITLE
Make AutoRenewTimeout works in less surprising way

### ISSUE THREAD

**Issue by rumatavz** [Particular/NServiceBus.AzureServiceBus#708]
For any developer(ok, for lazy developer, who havn't read all the documentation) it obvious that if he set AutoRenewTimeout(5 min) than my handler can work for 4:55 minutes without problems.

But in fact  if queue contains more than one message and PrefetchCount != 0 he can get MesageLockLostException.

This limitation is documented: AutoRenewTimeout applies to the currently processed messages.

But I think this limitation should be avoided. Here are my arguments
1) It's a surprising behavior. No one will expect AutoRenewTimeout to work with that limitations(even if these limitation are well documented).
2) The problem may arise in some scenarios that may be not tested. Moreover it will arise when the system heavy loaded(message handling takes more then usually, there are more messages in queue than usually)
3) Lost of the lock can cause two problems: false positive message handling errors(if the handler is not idempotent) and waste of system resources for redoing work in case of idempotent handlers. Taking in account that problem arises in load peaks it can be serious problem.

This strange behavior of AutoRenewTimeout is actually implemented in one of MS ASB client's API. Namely in OnMessageAsync API. 

But there is other possibility to improve AutoRenewTimeout NSB API param. It's get messages via queueClient.ReceiveBatch and call RenewLock on timer. It's the thing I suggest to implement.

**Comment by yvesgoeleven** [comment]
>It's get messages via queueClient.ReceiveBatch and call RenewLock on timer.

@rumatavz This suggestion is inaccurate. PrefetchCount also applies in to additional messages pulled using receivebatch and nservicebus won't get a handle to those messages until they are actually returned from the receivebatch method. We won't be able to renew the messages that are being prefetched, so it would behave the exact same way as the OnMessage api does today. I agree that it is somewhat surprising behavior, but there is nothing we can do to change that behavior besides setting prefetchcount to 0.

If you want this behavior to be changed, I suggest you open an issue for the servicebus sdk https://github.com/Azure/azure-service-bus-dotnet

**Comment by SeanFeldman** [comment]
@rumatavz one of the challenges with ASB as a transport is that the underlying ASB service is not trivial and documentation has never being so great. In the last year Microsoft team has improved it, but it's still not where it needs to be. Fortunately, changes are coming.

Receing messages and prefetching involves ASB client, but the broker (server side) has a lot to do with that as well. As @yvesgoeleven pointed out, using Batched received or OnMessage API is not going to change the fact that locks on buffered messages cannot be controlled by the client (old or new).

If you'd like to raise a documentation issue with Microsoft, a better issue tracker would be https://github.com/Azure/azure-service-bus/issues.

PS: will append this as a link to my reply on your support case. Thanks.

**Comment by rumatavz** [comment]
The reason why you use PrefetchCount is reducing roundtrips. For that purpose we can do the following code:
queueClient.PrefetchCount = 0;
var smth = queueClient.ReceiveBatch(GetNSBParams.PrefetchCount, ...

**Comment by SeanFeldman** [comment]
The transport is using Prefetch to optimize number of trips. That is correct.
The use of OnMessage API is advocated by the ASB team and has benefits over batched receive.
In your scenario, where roundtrips optimization is not necessary, disabling prefetching in the similar way you've outlined would do the job as well. The support case you've raised had an issue with lock duration more than the prefetch. Which was addressed with the [PR I've raised](https://github.com/rumatavz/NSBTest/pull/1).

Thank you for the suggestion. We're constantly looking at how to make the transport better and improvign this over the time. As for major changes, this transport cannot march into the brave new world of .NET Standard since the underlying MSFT ASB client doesn't support it. We'll be [building and leleasing a new ASB transport](https://particular.net/blog/a-new-azure-service-bus-transport-but-not-just-yet) in the future, based on the new MSFT ASB client that supports .NET Standard. Suggestions like the one you've provided will be evaluated.
