### ISSUE TITLE
Integrating NServiceBus consumers with non-NServiceBus publishers

### ISSUE THREAD

**Issue by DixonDs** [Particular/NServiceBus.AzureServiceBus#711]
I am looking into integration scenarios to allow services running with NServiceBus to consume messages sent by non-NServiceBus publishers i.e. no NServiceBus-specific headers are included in transport messages. It seems that one extension point that could potentially allow it is `IConvertBrokeredMessagesToIncomingMessages` (you can set a custom implementation with `UseBrokeredMessageToIncomingMessageConverter` extension method) but this API is marked as obsolete. Are there any other extension points that could be used? Of course, I can always rewrite the whole transport implementation, but I would like to avoid that if possible

**Comment by yvesgoeleven** [comment]
@DixonDs You can find a sample and further documentation up on how to do this without the converter here: https://docs.particular.net/transports/azure-service-bus/native-integration, but it varies a bit depending on your needs.

Non native senders usually send as raw stream instead of a binary formatted array (which is the default setting), you can change this using topologySettings.BrokeredMessageBodyType(SupportedBrokeredMessageBodyTypes.Stream);

If all you need to do additionally is add the headers on the receive side, then you can use any of these ways to add them before deserialization happens https://docs.particular.net/nservicebus/messaging/header-manipulation?version=core_7

If you also need to deserialize the body in a custom way, you need to create a serializer for your body format https://docs.particular.net/nservicebus/serialization/custom-serializer?version=core_7. Most standard formats already have a serializer though https://docs.particular.net/nservicebus/serialization/, so this is unlikely.
