### ISSUE TITLE
Completion Callback Tx Scope Review

### ISSUE THREAD

**Issue by abombss** [Particular/NServiceBus.AzureServiceBus#78]
https://github.com/Particular/NServiceBus.AzureServiceBus/blob/develop/src/Transport/Receiving/MessageReceiverNotifier.cs#L141

From past experience I would not recommend using a TransactionScope and instead use raw Tx and set the thread static Transaction.Current to the tx.  TransactionScope can cause some very flaky results with concurrency, even with AsyncReflow.  From what I know AsyncReflow doesn't do much to prevent other transactions enlisting in the scope accidently, it really just ensures the Tx is marshalled back on to the callback thread so it can complete.

The approach that has worked for me is to always just set the Transaction.Current directly and before awaiting the task set the Transaction.Current back to the previous value in a finally block.  Then you can call await Task.All.

Also, you can combine the OnComplete Tasks and the incoming Complete in Task.All instead of doing them serially, this will cut down on latency by sending everything together and potentially batching under the covers.  The TX ensures the incoming complete won't happen unless all the Sends succeed as well.

**Comment by SeanFeldman** [comment]
@adamralph good point on combining OnComplete tasks with the incoming msg completion task. 

As for the TransactionalScope, pinging @danielmarbach to provide some thoughts we had.

**Comment by danielmarbach** [comment]
Thanks @abombss for the suggestion. Unfortunately setting `Transaction.Current` could lead to serious issues. This is due to the fact that when you set `Transaction.Current` then only the old `legacy` context is used which does not properly float when used with asynchronous continuations. Here an extract from the `Transaction.Current` property setter

```
                // Support only legacy scenarios using TLS. 
                ContextData.TLSCurrentData.CurrentTransaction = value;
                // Clear CallContext data.
                CallContextCurrentData.ClearCurrentData(null, false);
```

So it is using the TLSCurrentData and clears everything in the proper call context.

If you are using the `TransactionScope` with `AsyncFlowOptionsEnabled` the following happens:

```
           if (this.AsyncFlowEnabled)
            {
                // Async Flow is enabled and CallContext will be used for ambient transaction. 
                this.threadContextData = CallContextCurrentData.CreateOrGetCurrentData(this.ContextKey);
 
                if (this.savedCurrentScope == null && this.savedCurrent == null)
                {
                    // Clear TLS data so that transaction doesn't leak from current thread.
                    ContextData.TLSCurrentData = null;                        
                }
            }
            else
            {
                // Legacy TransactionScope. Use TLS to track ambient transaction context.
                this.threadContextData = ContextData.TLSCurrentData;
                CallContextCurrentData.ClearCurrentData(this.ContextKey, false);
            }
```

The CallContextTLS is cleared and the proper call context receives the `CommitableTransaction`. Since only this one properly floats (due to the nature how it interacts with the `ExecutionContext`) the `CommitableTransaction` over asynchronous continuations we can only use TransactionScope.

Here are two tests to verify the behavior:

The async method being used.

```
        private static async Task SomeMethodInTheCallStackAsync()
        {
            Assert.NotNull(Transaction.Current);

            await Task.Delay(500).ConfigureAwait(false);

            Assert.NotNull(Transaction.Current);
        }
```

Using `CommitableTransaction`

```
        [Test]
        public async Task CommitableTransaction()
        {
            Assert.Null(Transaction.Current);

            try
            {
                var tx = new CommittableTransaction();
                Transaction.Current = tx;

                Assert.NotNull(Transaction.Current);

                await SomeMethodInTheCallStackAsync()
                    .ConfigureAwait(false);

                tx.Commit();
            }
            finally
            {
                Transaction.Current = null;
            }

            Assert.Null(Transaction.Current);
        }
```

The test immediately blows when `Task.Delay` returns and the continuation with the `Assert.NotNull(Transaction.Current)` statement is executed. Hence showing that the manual approach doesn't work.

On the other hand this works as expected

```
        [Test]
        public async Task TransactionScopeAsyncProper()
        {
            Assert.Null(Transaction.Current);

            using (var tx =
                new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
            {
                Assert.NotNull(Transaction.Current);

                await SomeMethodInTheCallStackAsync()
                    .ConfigureAwait(false);

                tx.Complete();
            }

            Assert.Null(Transaction.Current);
        }
```

**Comment by yvesgoeleven** [comment]
We'll stick with the transactionscope for now, issue to be reopened if this proves wrong
