### ISSUE TITLE
Callbacks with ASB

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureServiceBus#80]
Taskforce: @seanfeldman, @melkio 

## General Description

With NSB v6 supporting callbacks in a unified way (using NSB.Callbacks nuget package), it is decided to release NSB.ASB with callbacks support that used the unified implementation and not the native one. 

## Plan of Attack
- [x] verify unified callbacks work
- [x] update transport compatibility tests
- [x] smoke test using [sample code](http://docs.particular.net/samples/callbacks/)

### Native Option (original issue description)

Option of native support for callbacks using SessionReceiver.
![image](https://cloud.githubusercontent.com/assets/1309622/12155467/72e11334-b482-11e5-8808-7632599fe79c.png)

Spike repo: https://github.com/SeanFeldman/ASB.NativeCallback

**Comment by abombss** [comment]
+1, its a nice solution to deal with replies, I also know MT3 just implemented / spiked sagas using sessions and session state.  No 3rd party data store is required and its transactional.

A couple things to consider.

1) Whats the overhead like for lots of request / reply, every request requires a new session to listen to?  Are there quotas, limits, or resource overhead with having hundreds or even thousands of concurrent sessions open on a single queue within a single endpoint?

2) How do you deal with abandoned sessions?  In the spike, the listener for the reply is transient, if that endpoint goes down the reply will never get consumed... probably not a problem that reply is lost, the bigger issue is the reply's will get stuck / hung in the queue because when the endpoint starts back up it won't know it should clear out old sessions, whatever the solution is, it needs to also account for competing consumers (multiple instances of the endpoint running against the same queue).  You might need to think about storing state for the session and being able to do things like enumerate all the sessions QueueClient.GetMessageSessions() on startup to clean-up dead sessions or something.

Overall its a nice feature, it will support competing consumers well so if you are looking for reply to a web farm (multiple nodes) each node doesn't need its own queue, they can share the same queue and just use session id's to filter for their specific response.  It also may reduce latency in some scenarios since there is an active receive pending for a session as opposed to having to drain all the messages in the front of the queue to get to the actual reply.

Can a queue handle both sessions and non-sessions or would it require separate queue with sessions enabled that can't process messages without a session id?

**Comment by SeanFeldman** [comment]
Good questions @abombss.

For # 2 (abandoned sessions), if replies to callbacks are volotile That's how NSB callbacks behave today. The question is if we should support this. Today with NSB.ASB, if you want your web tier to use callbacks, you scale with queue per instance and then callbacks work w/o anything special in place.

**Comment by yvesgoeleven** [comment]
@abombs I think it all boils down to choice of sessionId, if sessionId is predictable f.e. EndpointInstanceId, then we can have a persistent session imo (untested, just my assumption)

**Comment by abombss** [comment]
Maybe I didn't articulate well. There needs to be a cleanup process for
sessions since they are volatile. I think volatile callbacks are fine since
that is what nsb uses today, however without a cleanup process I am going
to have unprocessed replies sitting in my queue forever.

Yves, not sure how a deterministic I'd helps here, I would still need a
mechanism to scan all open sessions looking for dead ones and deleting the
messages.

As for queue per instance that is not a good solution for auto scale and
ephemeral endpoints. Using sessions solves this problem so now we can use
normal competing consumers on a shared queue for all instances of an
endpoint and still gurantee the reply gets processed by the correct
instance.

**Comment by yvesgoeleven** [comment]
with a predictable & fixed session Id, we would actually reuse the same session over and over, so there would be no need to clean others up.

**Comment by abombss** [comment]
Why would you reuse the session id what's the advantage over just using a
queue then? A reply is applicable to only a single request unless you are
talking about multiple message correlation like sagas which is also a great
use case. By using the session id tied to each request you eliminate the
need for custom handling and routing, the callback is just waiting on its
session id.

**Comment by yvesgoeleven** [comment]
it would allow us to only manage a single callback receiver instead of many, no need to clean up abandoned sessions, it would allow us to pick up replies even after a reboot.

**Comment by SeanFeldman** [comment]
I've continued the spike and we can't use input queue for callbacks. ASB library will throw an exception if a message w/o session ID is sent to a queue that has `RequiresSession` set to true. It will also throw an exception if `QueueClient` or `MessageReceiver` is used with `Receive` operation. 

Therefore a callback queue needs to be a separate queue. Saying that, we can have just a single queue with multiple endpoints competing over it using their unique session ID.

**Comment by SeanFeldman** [comment]
Another option, is to require sessions on all of the queues. For normal messages, session id would be endpoint name (to allow competing consumers), and for callbacks to have instance id as a session id. This option could be much more challenging.

**Comment by abombss** [comment]
Is require session property needed to use sessions, or is it just there to
block messages without sessions.

**Comment by SeanFeldman** [comment]
`RequiresSession` is needed to use the sessions @abombss.
Based what I've seen so far, queue is either used with session-based messages, or without. But you can't mix both types of messages. ASB will throw an exception letting you know that:

> `InvalidOperationException`, ​_The SessionId was not set on a message, and it cannot be sent to the entity. Entities that have session support enabled can only receive messages that have the SessionId set to a valid value._​

**Comment by SeanFeldman** [comment]
Core related discussion: https://github.com/Particular/NServiceBus/issues/3369

**Comment by SeanFeldman** [comment]
@SzymonPobiega I'll need to connect with you over https://github.com/Particular/NServiceBus/issues/3369#issuecomment-184536667 to get more information on how we can implement callbacks in ASB.

**Comment by SzymonPobiega** [comment]
Would you be still around tomorrow 6:20 my time? I'll try to take a look at ASB source code to be up to date. Alternatively I can pair up with @Scooletz on this.

**Comment by SeanFeldman** [comment]
@SzymonPobiega can't promise that, it's 9:20PM my time.
@Scooletz is working on ASQ, but if you discus it with him.

**Comment by SeanFeldman** [comment]
@SzymonPobiega could we please connect? I'd like to finish callbacks for ASB. Thank you.

**Comment by mikeminutillo** [comment]
@SeanFeldman is there a taskforce working on this? Please update the issue description with a list of task force members. Also, please update the plan of attack with links to related sub-items.

**Comment by SeanFeldman** [comment]
@mikeminutillo taskforce - done. For the plan of attack, in case a simple check-list will suffice, do we need to have multiple issues? I don't quite see the value for those.

**Comment by tmasternak** [comment]
@SeanFeldman does it make sense to add anyone to the taskforce?

**Comment by SeanFeldman** [comment]
@tmasternak add to already listed people? Probably not.
