### ISSUE TITLE
Consider native DeadLettering a message that fails processing if MaxDeliveryCount is reached

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureServiceBus#82]
When NSB.ASB runs into an exception while processing an incoming message, [message is abandoned](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/1071bdceb1042d05ad9d0fe81aea0d6fb4f9f5f1/src/Transport/Receiving/MessageReceiverNotifier.cs#L169). 

There's one edge case where we're loosing an important information - if exception occurred ​_and_​ we've exhausted all of the delivery attempts, we know that the message will go into the DLQ. So why in that case rather than abandoning the message not to mark it as for DLQ with the exception that we've got?

This will allow messages in the DLQ to have the information about the exception that caused MaxDeliveryCount to be exhausted and sent it into DLQ.

**Caveat**

This will use increase `BrokeredMessage` total size as it will add exception details to the header.

@Particular/azure what do you think? Should we pursue this?

**Comment by abombss** [comment]
Yes, I documented this a long time ago, its related to #11 

Specifically we should be using native DLQ and forwarding and using the Abandon function which allows the updating of BrokeredMessage Properties.  This solves a couple major issues for us.

1) Lost error messages because of no 2pc.  The complete succeeds but send to the error queue fails.

2) Messages ending up in DLQ because of competing consumers and inaccurate tracking of delivery attempts.  The delivery attempts is kept in memory on the consumer endpoint, with competing consumers its possible a message is seen by multiple instances so the BrokeredMessage Delivery attempts can easily exceed the max thus causing the message to end up in the DLQ with no diagnostics.  This is very problematic for our ops teams to deal with.  The only option is to set our max attempts really high.  However this creates lots of unnecessary overhead and latency since there is no way to force a poison message we are stuck retrying a high number of times, and we are also still susceptible to point 1 above.

3) Messages ending up in DLQ with no info, not even a log message of an exception and no info about the endpoint where it failed.  We found this happens for 2 reasons: 1, invalid brokered message conversion will silently fail in v5 & v6 of the transport, not even a log message, 2nd because the receive batch size is way too high and locks are expiring in the background because there is no auto-renew mechanism #19.  Its a major problem for our Ops team today when this happens because we have zero diagnostics as to what happened and what endpoint the error occurred on.

**Comment by SeanFeldman** [comment]
Needs to be broken down into separate issues (will serve as an "root" issue)

**Comment by SeanFeldman** [comment]
This will be reviewed when NSB v6 is done.

**Comment by ramonsmits** [comment]
This StackOverflow mentions this DLQ behavior: 

http://stackoverflow.com/questions/36303008/nservicebus-messageforwardingincaseoffaultconfig-not-working-as-expected%3E

**Comment by SeanFeldman** [comment]
Fixed by the [new seam](https://github.com/Particular/NServiceBus.AzureServiceBus/issues/277).

**Comment by SeanFeldman** [comment]
@abombss forwarding from DLQs is also possible now, but not enabled by default. [Documentation](https://github.com/Particular/docs.particular.net/issues/1446) to come soon.
